# File: password-manager/docker-compose.yml
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: passmanager
      POSTGRES_USER: passmanageradmin
      POSTGRES_PASSWORD: Root@2025*


volumes:
  postgres_data:
