# File: password-manager/docker-compose.yml
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.passman.rule=Host(`password-manager.local`)"
      - "traefik.http.services.passman.loadbalancer.server.port=8000"
    networks:
      - traefik
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    networks:         
      - traefik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  traefik:
    external: true

volumes:
  postgres_data:
